import os

TELEGRAM_BOT_TOKEN = os.environ["TELEGRAM_BOT_TOKEN"]
TELEGRAM_CHAT_ID = os.environ["TELEGRAM_CHAT_ID"]
WC_API_KEY = os.environ["WC_API_KEY"]
DEFAULT_DISPLAY_TZ = os.environ.get("DISPLAY_TZ", "Europe/Zurich")

WC_API_BASE_URL = os.environ.get("WC_API_BASE_URL", "https://wc2026api.com/api/v1")

WATCHED_TEAM_CODES = {"SUI", "USA"}

LIVE_POLL_INTERVAL_MINUTES = 5
PRE_MATCH_ALERT_MINUTES_BEFORE = 2
MORNING_DIGEST_HOUR = 8
EVENING_RECAP_OFFSET_MINUTES_AFTER_KICKOFF = 120 + 30
